"""Prompt 模板模块"""

from .templates import (
    INTENT_PROMPT_TEMPLATE,
    REFINE_PROMPT_TEMPLATE,
    QUESTION_PROMPT_TEMPLATE,
    EXTEND_QUERY_PROMPT_TEMPLATE,
    SELECT_WEBPAGE_PROMPT_TEMPLATE,
    ANSWER_PROMPT_TEMPLATE,
)

__all__ = [
    "INTENT_PROMPT_TEMPLATE",
    "REFINE_PROMPT_TEMPLATE",
    "QUESTION_PROMPT_TEMPLATE",
    "EXTEND_QUERY_PROMPT_TEMPLATE",
    "SELECT_WEBPAGE_PROMPT_TEMPLATE",
    "ANSWER_PROMPT_TEMPLATE",
]